#!/bin/bash

if test -f ~/crontabsum
then
    if [ "$(cat ~/crontabsum)" != "$(md5sum /etc/crontab | cut -d " " -f 1)" ]
    then 
        md5sum /etc/crontab | cut -d " " -f 1 > ~/crontabsum
        echo "File /etc/crontab was modified" | mail -s "crontab modified" root
    fi
else
    md5sum /etc/crontab | cut -d " " -f 1 > ~/crontabsum
fi
#updade mail
#sudo apt-get update
#sudo apt-get install mailutils
#check emails - sudo cat /var/mail/user
#create scheduled task - add "0 0 * * * sh ~/04"
#crontab -e
